Add a root logger
Without this logger, production errors such as forgetting to run `collectstatic`
are swallowed and all you get is a 500 status response, which is difficult to
troubleshoot.

Here's before:

[28/Aug/2023 13:30:13] "GET / HTTP/1.1" 500 145

Here's after:

[28/Aug/2023 13:17:18] "GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'dist/app.css'