Pin PyYAML<6.0.
The dependency on PyYAML is currently not pinned and fails as of version 6.0,
released Oct 14 2021 (traceback below). This change pins PyYAML to a compatible version.

Traceback (most recent call last):
  File "[...]/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "[...]/env/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "[...]/code/src/sa_web/views.py", line 98, in index
    config.update(settings.SHAREABOUTS.get('CONTEXT', {}))
  File "[...]/code/src/sa_web/config.py", line 75, in update
    self.data.update(other)
  File "[...]/code/src/sa_web/config.py", line 59, in data
    self._yml = yaml.load(config_yml)
TypeError: load() missing 1 required positional argument: 'Loader'